=== ManojKumarPatnaik/CTS-Chennai-Java/XML/Xml_1/WebContent/Test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Test"
	xmlns:tns="http://www.example.org/Test" elementFormDefault="qualified">


	<element name="patient" type="tns:Patient" />

	<complexType name="Patient">

		<sequence>


			<element name="name" type="tns:nameMaxLength" />
			<element name="age" type="int" />
			<element name="gender" type="tns:genderType" />
			<element name="dob" type="date" />
			<element name="email" type="string" maxOccurs="unbounded" />
			<element name="phone" type="long" />
			<element name="payment" type="tns:PaymentType" />

		</sequence>

		<attribute name="id" type="tns:ID" />

	</complexType>

	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int" />
			<element name="insurence" type="tns:Insurence" />

		</choice>

	</complexType>
	<complexType name="Insurence">
		<all>
			<element name="provider" type="string" />
			<element name="limit" type="int" />
		</all>

	</complexType>

	<simpleType name="ID">

		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="nameMaxLength">
		<restriction base="string">
			<maxLength value="15"></maxLength>
		</restriction>
	</simpleType>

	<simpleType name="genderType">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />

		</restriction>
	</simpleType>



</schema>

=== ManojKumarPatnaik/CTS-Chennai-Java/XML/Xml_1/WebContent/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.example.org/Test"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Test Test.xsd ">
	<tns:name>xxx</tns:name>
	<tns:age>0</tns:age>
	<tns:gender>M</tns:gender>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>tns:email</tns:email>
	<tns:phone>0</tns:phone>
	
	<tns:payment>
		<tns:insurence>
			<tns:provider>djfhd</tns:provider>
			<tns:limit>434</tns:limit>
		</tns:insurence>
	</tns:payment>
</tns:patient>
