=== ManojKumarPatnaik/CTS-Chennai-Java/XML/XML-Schema-Demo/patientpayment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.praveen.com/patient"
	xmlns:tns="http://www.praveen.com/patient" elementFormDefault="qualified">

	<element name="patient" type="tns:Patient" />

	<complexType name="Patient">
		<sequence>
			
			<element name="name" type="tns:name15charlength" />
			<element name="age" type="tns:ageVal" />
			<element name="gender" type="tns:genderVal" />
			<element name="dob" type="date" />
			<element name="email" type="string" />
			<element name="phone" type="tns:phoneVal" />
			<element name="paymentType" type="tns:paymentType"/>
		</sequence>
		
		<attribute name="patId" type="int"/>

	</complexType>

	<complexType name="paymentType">
		<choice>
			<element name="cash" type="int"/>
			<element name="insurence" type="tns:Insurence"/>
		</choice>
	</complexType>


	<complexType name="Insurence">
			<all>
				<element name="provider" type="string"/>
				<element name="limit" type="int"/>
			</all>
	</complexType>

	<simpleType name="phoneVal">
		<restriction base="string">
			<maxLength value="10" />
			<minLength value="10" />
			<pattern value="[0-9]*"></pattern>
		</restriction>

	</simpleType>

	<simpleType name="ageVal">
		<restriction base="int">
			<minInclusive value="1" />
		</restriction>


	</simpleType>

	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-8]*"></pattern>
		</restriction>
	</simpleType>


	<simpleType name="name15charlength">
		<restriction base="string">
			<maxLength value="15" />
			<pattern value="[A-Z]*"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="genderVal">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>




</schema>

=== ManojKumarPatnaik/CTS-Chennai-Java/XML/XML-Schema-Demo/patient_v3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.praveen.com/patient"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.praveen.com/patient patientpayment.xsd "
	patId="1024"
	>
	<tns:name>AAAA</tns:name>
	<tns:age>1</tns:age>
	<tns:gender>M</tns:gender>
	<tns:dob>2001-01-01</tns:dob>
	<tns:email>tns:email</tns:email>
	<tns:phone>1111111111</tns:phone>
	<tns:paymentType>
		<tns:insurence>
			<tns:limit>7645786</tns:limit>
			<tns:provider>ICICI</tns:provider>
		</tns:insurence>

	</tns:paymentType>
</tns:patient>
